In [263]:
import time
import numba
import numpy as np
from numba import guvectorize
from numba import guvectorize, float32, float64

In [264]:
# The target keyword decorator for loss and error return

def gu_loss(func, *args, **kwargs):
    """
    The guvectorize decorated method, runs in nopython mode
    :param func: a loss error method
    :param target: choose between | 1: None -> serial | 2: 'parallel' -> parallel | execution method
    :return: the decorated loss, error function
    """
    kwargs_ = {k: v for k, v in kwargs.items() if v is not None}
    return guvectorize([(float32[:], float32[:], float32[:], float32[:]),
                      (float64[:], float64[:], float64[:], float64[:])],
                     '(n),(n)->(),(n)', nopython=True, *args, **kwargs_)(func)

In [265]:
def mse(x, y, loss, derivation):
    for i in range(y.shape[0]):
        derivation[i] = y[i] - x[i]
    loss[0] = 0.5 * np.sum(derivation[:]**2)

def cross_entropy(x, y, loss, derivation):
    l = np.log(y[:]+1e-12)
    for i in range(y.shape[0]):
        if y[i] == 0:
            derivation[i] = 0.
        elif y[i] != 0:
            derivation[i] = -x[i]/y[i]
        loss[0] = -np.sum(x[:] * l)

def mse_py(yd, yp):
    e = yp - yd
    loss = 0.5 * np.sum(e**2)
    return loss, e

def xentropy(yd, yp):
    l = np.log(yp)
    loss = -np.sum(yd * l)
    deriv = -(yd/yp)
    return loss, deriv

In [266]:
a = np.arange(5, dtype=np.float32)
b = np.arange(10, 15, dtype=np.float32)

a, b

(array([0., 1., 2., 3., 4.], dtype=float32),
 array([10., 11., 12., 13., 14.], dtype=float32))

In [267]:
s_mse = gu_loss(mse)
p_mse = gu_loss(mse, target="parallel")
s_ce = gu_loss(cross_entropy)
p_ce = gu_loss(cross_entropy, target="parallel")


In [268]:
def ntime(func1):
    start = time.time()
    func1(a, b)
    end = time.time()
    print("Elapsed Numba Pre = %s" % (end - start))
    start = time.time()
    f2 = func1(a, b)
    end = time.time()
    print("Elapsed Numba Post = %s" % (end - start))
    return f2

def ptime(func1):
    start = time.time()
    f1 = func1(a, b)
    end = time.time()
    print("Elapsed PyTime = %s" % (end - start))
    return f1

In [269]:
print("MSE")
mse1 = ntime(s_mse)
mse2 = ptime(mse_py)
mse1, mse2



MSE
Elapsed Numba Pre = 2.2172927856445312e-05
Elapsed Numba Post = 8.821487426757812e-06
Elapsed PyTime = 6.556510925292969e-05


((250.0, array([10., 10., 10., 10., 10.], dtype=float32)),
 (250.0, array([10., 10., 10., 10., 10.], dtype=float32)))

In [270]:
print("CE")
ce1 = ntime(s_ce)
ce2 = ptime(xentropy)
ce1, ce2

CE
Elapsed Numba Pre = 2.5033950805664062e-05
Elapsed Numba Post = 9.5367431640625e-06
Elapsed PyTime = 0.0014576911926269531


((-25.618786,
  array([-0.        , -0.09090909, -0.16666667, -0.23076923, -0.2857143 ],
        dtype=float32)),
 (-25.618786,
  array([-0.        , -0.09090909, -0.16666667, -0.23076923, -0.2857143 ],
        dtype=float32)))

In [271]:
s_ce(np.array([0,0, 0]), np.array([0, 0, 0]))

(-0.0, array([0., 0., 0.]))

In [272]:
xentropy(np.array([0.,0, 0]), np.array([0, 0, 0]))

<ipython-input-265-66e2f4cd75a8>:21: RuntimeWarning: divide by zero encountered in log
  l = np.log(yp)
<ipython-input-265-66e2f4cd75a8>:22: RuntimeWarning: invalid value encountered in multiply
  loss = -np.sum(yd * l)
<ipython-input-265-66e2f4cd75a8>:23: RuntimeWarning: invalid value encountered in true_divide
  deriv = -(yd/yp)


(nan, array([nan, nan, nan]))